export type JenisTerbitan = 'koran' | 'jurnal' | 'majalah' | 'buletin';

export interface Article {
  id: string;
  judul: string;
  pengarang: string;
  subjek: string[];
  abstrak: string;
  namaMedia: string;
  jenisTerbitan: JenisTerbitan;
  volume?: string;
  nomor?: string;
  tanggalTerbit: string;
  tahunTerbit: number;
  halamanKolom: string;
  kataKunci: string[];
  lokasiKoleksi: string;
  issn?: string;
  fotoUrl?: string;
}

export const subjects = [
  'Literasi Digital',
  'Literasi Anak',
  'Pustakawan & Perpustakaan',
  'Bahasa & Budaya',
  'Pendidikan',
  'Teknologi Informasi',
  'Ekonomi & Bisnis',
  'Kesehatan',
  'Sosial Politik',
  'Seni & Sastra',
];

export const mediaList = [
  { nama: 'Radar Blitar', jenis: 'koran' as JenisTerbitan },
  { nama: 'Kompas', jenis: 'koran' as JenisTerbitan },
  { nama: 'Media Indonesia', jenis: 'koran' as JenisTerbitan },
  { nama: 'Republika', jenis: 'koran' as JenisTerbitan },
  { nama: 'Jawa Pos', jenis: 'koran' as JenisTerbitan },
  { nama: 'Suara Merdeka', jenis: 'koran' as JenisTerbitan },
  { nama: 'Pikiran Rakyat', jenis: 'koran' as JenisTerbitan },
  { nama: 'Kedaulatan Rakyat', jenis: 'koran' as JenisTerbitan },
  { nama: 'Memorandum', jenis: 'koran' as JenisTerbitan },
  { nama: 'Surya', jenis: 'koran' as JenisTerbitan },
];

// Import images
import klipingMinatBaca from '@/assets/kliping/minat-baca-membaik.png';
import klipingDesainGrafis1 from '@/assets/kliping/literasi-desain-grafis-1.png';
import klipingDesainGrafis2 from '@/assets/kliping/literasi-desain-grafis-2.png';
import klipingDesainGrafis3 from '@/assets/kliping/literasi-desain-grafis-3.png';
import klipingPelatihanMenulis from '@/assets/kliping/pelatihan-menulis-konten.png';
import klipingWastraNusantara from '@/assets/kliping/literasi-wastra-nusantara.png';
import klipingVlogging from '@/assets/kliping/literasi-vlogging.png';
import klipingBordir from '@/assets/kliping/literasi-bordir.png';
import klipingKekuasaanBahasa from '@/assets/kliping/kekuasaan-bersenjata-bahasa.png';

export const sampleArticles: Article[] = [
  // Articles with real clipping photos
  {
    id: '1',
    judul: 'Minat Baca Membaik, Durasi Masih Pendek',
    pengarang: 'Tim Redaksi Jawa Pos',
    subjek: ['Literasi Anak', 'Pendidikan'],
    abstrak: 'Gubernur Khofifah Indar Parawansa menyampaikan bahwa tingkat literasi masyarakat Jatim makin membaik. Namun, ada pula tantangan besarnya. Durasi membaca masyarakat di Jatim masih tergolong pendek. Selain itu, yang perlu dibenahi adalah sektor literasi digital. Angka ini lebih tinggi daripada minat baca secara nasional yang mencapai 59,5 persen.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-18',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 6, Kol. 1-4',
    kataKunci: ['minat baca', 'literasi digital', 'Jawa Timur', 'Khofifah', 'Festival Hari Buku Nasional'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '2',
    judul: 'Literasi Desain Grafis tentang Bung Karno, Wujudkan Masyarakat Gemar Berkreasi',
    pengarang: 'Sanaviyen Isdar Bhara',
    subjek: ['Bahasa & Budaya', 'Seni & Sastra', 'Pendidikan'],
    abstrak: 'UPT Perpustakaan Proklamator Bung Karno menggelar Literasi Desain Grafis tentang Bung Karno. Kegiatan tersebut diikuti oleh 100 peserta yang terdiri atas pelajar, mahasiswa, dan masyarakat umum. Narasumber yang dihadirkan, yakni Garva Master Arang Moeljono memberikan penjelasan tentang desain grafis yang berkualitas.',
    namaMedia: 'Memorandum',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-11',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-5',
    kataKunci: ['desain grafis', 'Bung Karno', 'literasi', 'perpustakaan', 'kreativitas'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '3',
    judul: 'Literasi Desain Grafis tentang Bung Karno, Wujudkan Masyarakat Gemar Berkreasi',
    pengarang: 'Tim UPT Perpustakaan Proklamator Bung Karno',
    subjek: ['Bahasa & Budaya', 'Seni & Sastra'],
    abstrak: 'Perpustakaan Proklamator Bung Karno mengadakan kegiatan literasi desain grafis dengan tujuan mewujudkan masyarakat yang gemar berkreasi. Kegiatan ini mendukung kesejahteraan masyarakat melalui pengembangan keterampilan desain grafis yang dapat diterapkan dalam berbagai bidang.',
    namaMedia: 'Radar Blitar',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-17',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-4',
    kataKunci: ['desain grafis', 'Bung Karno', 'kreativitas', 'perpustakaan'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingDesainGrafis1,
  },
  {
    id: '4',
    judul: 'Literasi Desain Grafis tentang Bung Karno, Bekal Tingkatkan Kesejahteraan',
    pengarang: 'Sanaviyen Isdar Bhara',
    subjek: ['Bahasa & Budaya', 'Ekonomi & Bisnis', 'Pendidikan'],
    abstrak: 'UPT Perpustakaan Proklamator Bung Karno menyelenggarakan kegiatan literasi desain grafis sebagai bekal meningkatkan kesejahteraan masyarakat. Kegiatan ini mengajarkan keterampilan desain yang dapat dimanfaatkan untuk mengembangkan usaha kreatif dan meningkatkan pendapatan masyarakat.',
    namaMedia: 'Memorandum',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-21',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 1-5',
    kataKunci: ['desain grafis', 'kesejahteraan', 'Bung Karno', 'literasi', 'ekonomi kreatif'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingDesainGrafis3,
  },
  {
    id: '5',
    judul: 'Peserta Pelatihan Menulis Konten Kreatif Dinas Perpustakaan dan Arsip Kabupaten Blitar',
    pengarang: 'Nia Yuliana',
    subjek: ['Literasi Digital', 'Pustakawan & Perpustakaan', 'Pendidikan'],
    abstrak: 'Dinas Perpustakaan dan Arsip Kabupaten Blitar menggelar pelatihan menulis konten kreatif yang diikuti oleh 35 peserta. Pelatihan ini bertujuan meningkatkan kemampuan peserta dalam membuat konten digital yang menarik dan informatif untuk mendukung promosi perpustakaan dan kegiatan literasi.',
    namaMedia: 'Radar Blitar',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-03-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 1-4',
    kataKunci: ['konten kreatif', 'pelatihan', 'perpustakaan', 'Blitar', 'literasi digital'],
    lokasiKoleksi: 'Arsip Koran Mar 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '6',
    judul: 'Literasi Wastra Nusantara, Lestarikan dan Gairahkan Budaya Bangsa',
    pengarang: 'Tim Redaksi Surya',
    subjek: ['Bahasa & Budaya', 'Seni & Sastra'],
    abstrak: 'Dalam Literasi Wastra Nusantara ada beberapa busana khas Indonesia. Salah satu busananya, menarik wastra Nusantara dalam kehidupan sehari-hari. Hal ini menjadi dilakukan Kesayangan Pengarang Indonesia dan Karya Batik Nusantara yang bertransformasi perpustakaan menjadi ruang untuk mempromosikan budaya Indonesia.',
    namaMedia: 'Surya',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-04-13',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-5',
    kataKunci: ['wastra nusantara', 'budaya', 'batik', 'literasi', 'tradisi Indonesia'],
    lokasiKoleksi: 'Arsip Koran Apr 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '7',
    judul: 'Literasi Vlogging, Tumbuhkan Masyarakat Gemar Berkreasi',
    pengarang: 'Tim Redaksi Memorandum',
    subjek: ['Literasi Digital', 'Teknologi Informasi', 'Seni & Sastra'],
    abstrak: 'Kegiatan yang ada di UPT Perpustakaan Proklamator Bung Karno diantaranya Literasi Vlogging dengan rincian total 35 peserta. Acara bertujuan menumbuhkan kemampuan masyarakat dalam membuat konten video kreatif. Para peserta difasilitasi untuk mengikuti kegiatan literasi vlogging oleh pelatih profesional.',
    namaMedia: 'Memorandum',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-06-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-4',
    kataKunci: ['vlogging', 'literasi digital', 'kreativitas', 'konten video', 'perpustakaan'],
    lokasiKoleksi: 'Arsip Koran Jun 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '8',
    judul: 'Asah dan Kembangkan Kreativitas Melalui Literasi Bordir',
    pengarang: 'Tim Redaksi Radar Blitar',
    subjek: ['Seni & Sastra', 'Bahasa & Budaya', 'Ekonomi & Bisnis'],
    abstrak: 'UPT Perpustakaan Proklamator Bung Karno menggelar Literasi Bordir dengan tujuan mengasah dan mengembangkan kreativitas masyarakat. Kegiatan ini diikuti oleh puluhan peserta yang belajar teknik bordir tradisional maupun modern. Narasumber memberikan pelatihan langsung untuk membuat produk bordir yang berkualitas.',
    namaMedia: 'Radar Blitar',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 1-4',
    kataKunci: ['bordir', 'kreativitas', 'kerajinan tangan', 'literasi', 'ekonomi kreatif'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '9',
    judul: 'Kekuasaan Itu Bersenjata Bahasa',
    pengarang: 'Hasryo Nurcahyo',
    subjek: ['Bahasa & Budaya', 'Sosial Politik'],
    abstrak: 'Ulasan dalam artikel ini membahas tentang kekuatan bahasa sebagai instrumen kekuasaan. Bahasa tidak hanya sebagai alat komunikasi tetapi juga sebagai senjata yang dapat mempengaruhi opini publik dan menggerakkan massa. Artikel ini menganalisis bagaimana bahasa digunakan dalam konteks politik dan sosial.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-28',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 6, Kol. 1-5',
    kataKunci: ['bahasa', 'kekuasaan', 'politik', 'komunikasi', 'opini publik'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  // Additional 91 articles for 2024
  {
    id: '10',
    judul: 'Indeks Pembangunan Literasi Masyarakat Meningkat Signifikan',
    pengarang: 'Ahmad Fauzi',
    subjek: ['Literasi Anak', 'Pendidikan', 'Sosial Politik'],
    abstrak: 'Indeks Pembangunan Literasi Masyarakat (IPLM) menunjukkan peningkatan signifikan di berbagai daerah. Data terbaru menunjukkan bahwa upaya pemerintah dalam meningkatkan minat baca mulai membuahkan hasil positif.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-01-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 1-4',
    kataKunci: ['IPLM', 'literasi masyarakat', 'minat baca', 'pendidikan'],
    lokasiKoleksi: 'Arsip Koran Jan 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '11',
    judul: 'Perpustakaan Keliling Jangkau Pelosok Desa',
    pengarang: 'Dewi Anggraini',
    subjek: ['Pustakawan & Perpustakaan', 'Pendidikan'],
    abstrak: 'Program perpustakaan keliling terus menjangkau wilayah pedesaan yang jauh dari akses perpustakaan. Layanan ini disambut antusias oleh masyarakat terutama anak-anak usia sekolah yang haus akan bacaan.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-01-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 2-5',
    kataKunci: ['perpustakaan keliling', 'desa', 'akses literasi', 'layanan perpustakaan'],
    lokasiKoleksi: 'Arsip Koran Jan 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '12',
    judul: 'Festival Literasi Sekolah Dasar se-Jawa Timur',
    pengarang: 'Budi Santoso',
    subjek: ['Literasi Anak', 'Pendidikan'],
    abstrak: 'Festival Literasi Sekolah Dasar digelar untuk memotivasi siswa dalam mengembangkan budaya membaca. Berbagai lomba dan kegiatan kreatif diadakan untuk menarik minat anak-anak.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-01-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 1-4',
    kataKunci: ['festival literasi', 'sekolah dasar', 'Jawa Timur', 'budaya baca'],
    lokasiKoleksi: 'Arsip Koran Jan 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '13',
    judul: 'Digitalisasi Arsip Koran Kuno di Perpustakaan Nasional',
    pengarang: 'Rina Wulandari',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi'],
    abstrak: 'Perpustakaan Nasional terus melakukan digitalisasi arsip koran kuno untuk melestarikan sejarah pers Indonesia. Proyek ini memungkinkan masyarakat mengakses arsip secara daring.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-01-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 1-3',
    kataKunci: ['digitalisasi', 'arsip koran', 'Perpustakaan Nasional', 'sejarah pers'],
    lokasiKoleksi: 'Arsip Koran Jan 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '14',
    judul: 'Gerakan Literasi Sekolah Tingkatkan Prestasi Akademik',
    pengarang: 'Sri Wahyuni',
    subjek: ['Literasi Anak', 'Pendidikan'],
    abstrak: 'Penelitian menunjukkan bahwa sekolah yang aktif menerapkan Gerakan Literasi Sekolah (GLS) mengalami peningkatan prestasi akademik siswa secara signifikan.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-01-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 2-4',
    kataKunci: ['GLS', 'prestasi akademik', 'literasi sekolah', 'pendidikan'],
    lokasiKoleksi: 'Arsip Koran Jan 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '15',
    judul: 'Komunitas Baca Aktif Dorong Literasi Warga',
    pengarang: 'Hendra Wijaya',
    subjek: ['Pustakawan & Perpustakaan', 'Sosial Politik'],
    abstrak: 'Komunitas baca yang tersebar di berbagai kota terus aktif menggerakkan literasi warga. Kegiatan diskusi buku dan bedah novel rutin diadakan untuk menumbuhkan minat baca.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 1-4',
    kataKunci: ['komunitas baca', 'literasi warga', 'diskusi buku', 'minat baca'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '16',
    judul: 'Taman Bacaan Masyarakat Raih Penghargaan Nasional',
    pengarang: 'Linda Kartika',
    subjek: ['Pustakawan & Perpustakaan', 'Pendidikan'],
    abstrak: 'Taman Bacaan Masyarakat (TBM) dari berbagai daerah meraih penghargaan dalam ajang kompetisi tingkat nasional. Keberhasilan ini menjadi motivasi untuk terus mengembangkan layanan literasi.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 1-3',
    kataKunci: ['TBM', 'penghargaan', 'literasi', 'layanan masyarakat'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '17',
    judul: 'Pelatihan Pustakawan Digital Era 4.0',
    pengarang: 'Agus Prasetyo',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi'],
    abstrak: 'Pelatihan kompetensi digital untuk pustakawan digelar untuk menyiapkan tenaga perpustakaan menghadapi era industri 4.0. Materi mencakup pengelolaan perpustakaan digital dan layanan daring.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 2-5',
    kataKunci: ['pustakawan digital', 'industri 4.0', 'kompetensi', 'perpustakaan digital'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '18',
    judul: 'Program Dongeng Keliling Meriahkan Desa',
    pengarang: 'Retno Wulandari',
    subjek: ['Literasi Anak', 'Bahasa & Budaya'],
    abstrak: 'Program dongeng keliling sukses memikat anak-anak di berbagai desa. Kegiatan ini tidak hanya menghibur tetapi juga menanamkan nilai-nilai moral dan kecintaan pada literasi sejak dini.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 1-4',
    kataKunci: ['dongeng', 'literasi anak', 'nilai moral', 'pendidikan karakter'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '19',
    judul: 'Kolaborasi Perpustakaan dan Museum Tingkatkan Edukasi',
    pengarang: 'Dimas Kurniawan',
    subjek: ['Pustakawan & Perpustakaan', 'Bahasa & Budaya'],
    abstrak: 'Kolaborasi antara perpustakaan dan museum menciptakan pengalaman edukasi yang lebih komprehensif bagi pengunjung. Program terpadu ini menggabungkan literasi dengan pengenalan sejarah dan budaya.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 16, Kol. 1-5',
    kataKunci: ['perpustakaan', 'museum', 'edukasi', 'kolaborasi', 'sejarah'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '20',
    judul: 'Inovasi Layanan Perpustakaan Berbasis Aplikasi',
    pengarang: 'Fitri Handayani',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi', 'Literasi Digital'],
    abstrak: 'Beberapa perpustakaan daerah meluncurkan aplikasi mobile untuk memudahkan pemustaka mengakses layanan. Fitur peminjaman daring dan katalog digital menjadi andalan aplikasi ini.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 2-4',
    kataKunci: ['aplikasi perpustakaan', 'layanan digital', 'peminjaman online', 'inovasi'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingDesainGrafis1,
  },
  {
    id: '21',
    judul: 'Seminar Nasional Pengembangan Literasi Informasi',
    pengarang: 'Prof. Dr. Sulistyo',
    subjek: ['Pustakawan & Perpustakaan', 'Pendidikan', 'Literasi Digital'],
    abstrak: 'Seminar nasional pengembangan literasi informasi menghadirkan pakar dari berbagai universitas. Pembahasan fokus pada strategi meningkatkan kemampuan literasi informasi di era digital.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-03-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 1-4',
    kataKunci: ['seminar', 'literasi informasi', 'era digital', 'pendidikan tinggi'],
    lokasiKoleksi: 'Arsip Koran Mar 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '22',
    judul: 'Hibah Buku untuk Sekolah di Daerah Tertinggal',
    pengarang: 'Yanto Setiawan',
    subjek: ['Pendidikan', 'Sosial Politik'],
    abstrak: 'Program hibah buku berhasil menyalurkan ribuan eksemplar ke sekolah-sekolah di daerah tertinggal. Kegiatan ini merupakan kerja sama antara pemerintah dan berbagai komunitas peduli literasi.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-03-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 2-5',
    kataKunci: ['hibah buku', 'daerah tertinggal', 'pendidikan', 'donasi'],
    lokasiKoleksi: 'Arsip Koran Mar 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '23',
    judul: 'Workshop Menulis Kreatif untuk Guru',
    pengarang: 'Diana Kusuma',
    subjek: ['Pendidikan', 'Seni & Sastra'],
    abstrak: 'Workshop menulis kreatif digelar untuk meningkatkan kemampuan guru dalam mengajarkan literasi kepada siswa. Peserta belajar teknik menulis yang dapat diterapkan dalam pembelajaran.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-03-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-3',
    kataKunci: ['workshop', 'menulis kreatif', 'guru', 'pembelajaran'],
    lokasiKoleksi: 'Arsip Koran Mar 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '24',
    judul: 'Literasi Keuangan untuk Pemuda Desa',
    pengarang: 'Eko Purwanto',
    subjek: ['Ekonomi & Bisnis', 'Pendidikan'],
    abstrak: 'Program literasi keuangan menyasar pemuda di pedesaan untuk meningkatkan pemahaman tentang pengelolaan keuangan. Materi mencakup tabungan, investasi, dan wirausaha.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-03-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 2-5',
    kataKunci: ['literasi keuangan', 'pemuda', 'desa', 'wirausaha'],
    lokasiKoleksi: 'Arsip Koran Mar 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '25',
    judul: 'Pameran Buku Antik Menarik Perhatian Kolektor',
    pengarang: 'Hasan Basri',
    subjek: ['Bahasa & Budaya', 'Seni & Sastra'],
    abstrak: 'Pameran buku antik menghadirkan koleksi langka dari berbagai era. Acara ini menarik perhatian para kolektor dan pecinta buku dari seluruh Indonesia.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-03-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 1-4',
    kataKunci: ['pameran', 'buku antik', 'kolektor', 'sejarah'],
    lokasiKoleksi: 'Arsip Koran Mar 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '26',
    judul: 'Penguatan Literasi Digital untuk Lansia',
    pengarang: 'Siti Rahayu',
    subjek: ['Literasi Digital', 'Kesehatan', 'Sosial Politik'],
    abstrak: 'Program penguatan literasi digital untuk lansia bertujuan membantu mereka beradaptasi dengan teknologi. Materi dasar penggunaan smartphone dan internet menjadi fokus utama.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-04-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 2-4',
    kataKunci: ['literasi digital', 'lansia', 'teknologi', 'internet'],
    lokasiKoleksi: 'Arsip Koran Apr 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '27',
    judul: 'Kompetisi Menulis Cerpen Tingkat Nasional',
    pengarang: 'Wahyu Hidayat',
    subjek: ['Seni & Sastra', 'Pendidikan'],
    abstrak: 'Kompetisi menulis cerpen tingkat nasional digelar untuk menjaring penulis muda berbakat. Ribuan karya masuk dari seluruh penjuru Indonesia.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-04-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-3',
    kataKunci: ['cerpen', 'kompetisi', 'penulis muda', 'sastra'],
    lokasiKoleksi: 'Arsip Koran Apr 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '28',
    judul: 'Gerakan Bersih Sampah Literasi di Taman Kota',
    pengarang: 'Andi Firmansyah',
    subjek: ['Sosial Politik', 'Bahasa & Budaya'],
    abstrak: 'Gerakan bersih sampah literasi menggabungkan kegiatan lingkungan dengan promosi buku. Relawan membersihkan taman sambil membagikan buku gratis kepada pengunjung.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-04-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 2-5',
    kataKunci: ['lingkungan', 'literasi', 'taman kota', 'relawan'],
    lokasiKoleksi: 'Arsip Koran Apr 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '29',
    judul: 'Perpustakaan Umum Buka Layanan 24 Jam',
    pengarang: 'Bambang Sutejo',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi'],
    abstrak: 'Beberapa perpustakaan umum mulai membuka layanan 24 jam dengan sistem otomasi. Inovasi ini disambut positif oleh masyarakat yang membutuhkan akses fleksibel.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-04-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 1-4',
    kataKunci: ['perpustakaan 24 jam', 'layanan', 'otomasi', 'akses'],
    lokasiKoleksi: 'Arsip Koran Apr 2024',
    fotoUrl: klipingDesainGrafis1,
  },
  {
    id: '30',
    judul: 'Diskusi Buku Sejarah Proklamator Indonesia',
    pengarang: 'Dr. Nugroho Adi',
    subjek: ['Bahasa & Budaya', 'Pendidikan', 'Sosial Politik'],
    abstrak: 'Diskusi buku tentang sejarah proklamator Indonesia menghadirkan sejarawan dan akademisi. Pembahasan mendalam tentang perjuangan dan pemikiran para pendiri bangsa.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-04-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 1-5',
    kataKunci: ['sejarah', 'proklamator', 'diskusi buku', 'pendidikan'],
    lokasiKoleksi: 'Arsip Koran Apr 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '31',
    judul: 'Peringatan Hari Buku Nasional 2024',
    pengarang: 'Tim Redaksi Kompas',
    subjek: ['Bahasa & Budaya', 'Pustakawan & Perpustakaan'],
    abstrak: 'Peringatan Hari Buku Nasional 2024 digelar dengan berbagai rangkaian kegiatan. Festival buku, bedah buku, dan pameran menjadi daya tarik utama acara.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-17',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-4',
    kataKunci: ['Hari Buku Nasional', 'festival', 'pameran', 'literasi'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '32',
    judul: 'Launching Aplikasi Perpustakaan Digital Daerah',
    pengarang: 'Rudi Hartono',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi', 'Literasi Digital'],
    abstrak: 'Pemerintah daerah meluncurkan aplikasi perpustakaan digital untuk memudahkan akses masyarakat terhadap koleksi buku. Fitur e-book dan audiobook tersedia dalam aplikasi.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 2-4',
    kataKunci: ['aplikasi', 'perpustakaan digital', 'e-book', 'audiobook'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '33',
    judul: 'Pelatihan Penulisan Artikel Ilmiah untuk Mahasiswa',
    pengarang: 'Dr. Maria Susanti',
    subjek: ['Pendidikan', 'Seni & Sastra'],
    abstrak: 'Pelatihan penulisan artikel ilmiah digelar untuk meningkatkan kemampuan publikasi mahasiswa. Peserta belajar teknik menulis yang sesuai standar jurnal internasional.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 1-4',
    kataKunci: ['artikel ilmiah', 'mahasiswa', 'publikasi', 'jurnal'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '34',
    judul: 'Sosialisasi Literasi Hoaks di Media Sosial',
    pengarang: 'Fajar Nugroho',
    subjek: ['Literasi Digital', 'Teknologi Informasi', 'Sosial Politik'],
    abstrak: 'Sosialisasi literasi hoaks dilakukan untuk meningkatkan kemampuan masyarakat dalam memfilter informasi di media sosial. Peserta diajarkan cara mengidentifikasi berita palsu.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 2-5',
    kataKunci: ['hoaks', 'media sosial', 'literasi digital', 'informasi'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '35',
    judul: 'Lomba Bercerita untuk Anak TK dan SD',
    pengarang: 'Endang Lestari',
    subjek: ['Literasi Anak', 'Pendidikan'],
    abstrak: 'Lomba bercerita untuk anak TK dan SD digelar dalam rangka menumbuhkan kecintaan membaca sejak dini. Ratusan peserta tampil dengan kreativitas masing-masing.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 1-3',
    kataKunci: ['lomba bercerita', 'anak', 'TK', 'SD', 'literasi'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '36',
    judul: 'Perpustakaan Ramah Difabel Diresmikan',
    pengarang: 'Kartika Dewi',
    subjek: ['Pustakawan & Perpustakaan', 'Kesehatan', 'Sosial Politik'],
    abstrak: 'Perpustakaan ramah difabel resmi dibuka untuk melayani masyarakat berkebutuhan khusus. Fasilitas khusus seperti buku braille dan audiobook tersedia lengkap.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 2-4',
    kataKunci: ['perpustakaan difabel', 'braille', 'audiobook', 'inklusif'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingDesainGrafis3,
  },
  {
    id: '37',
    judul: 'Bedah Buku Novel Best Seller Karya Penulis Lokal',
    pengarang: 'Indra Gunawan',
    subjek: ['Seni & Sastra', 'Bahasa & Budaya'],
    abstrak: 'Acara bedah buku novel best seller karya penulis lokal dihadiri ratusan penggemar. Penulis berbagi pengalaman dan proses kreatif dalam menciptakan karyanya.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-30',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-4',
    kataKunci: ['bedah buku', 'novel', 'penulis lokal', 'sastra'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '38',
    judul: 'Kampanye Literasi Melalui Mural Kota',
    pengarang: 'Yoga Pratama',
    subjek: ['Seni & Sastra', 'Bahasa & Budaya', 'Sosial Politik'],
    abstrak: 'Kampanye literasi dilakukan melalui pembuatan mural bertema buku dan membaca di berbagai sudut kota. Seni jalanan ini menarik perhatian warga dan wisatawan.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-06-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 16, Kol. 2-5',
    kataKunci: ['mural', 'seni jalanan', 'kampanye literasi', 'kota'],
    lokasiKoleksi: 'Arsip Koran Jun 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '39',
    judul: 'Literasi Sains untuk Anak Melalui Eksperimen',
    pengarang: 'Dra. Sari Indah',
    subjek: ['Literasi Anak', 'Pendidikan', 'Teknologi Informasi'],
    abstrak: 'Program literasi sains mengajarkan konsep ilmu pengetahuan melalui eksperimen sederhana. Anak-anak antusias mengikuti kegiatan yang menyenangkan ini.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-06-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 1-3',
    kataKunci: ['literasi sains', 'eksperimen', 'anak', 'pendidikan'],
    lokasiKoleksi: 'Arsip Koran Jun 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '40',
    judul: 'Digitalisasi Manuskrip Kuno Nusantara',
    pengarang: 'Prof. Suryadi',
    subjek: ['Bahasa & Budaya', 'Teknologi Informasi', 'Pustakawan & Perpustakaan'],
    abstrak: 'Proyek digitalisasi manuskrip kuno Nusantara terus berjalan untuk melestarikan warisan budaya. Koleksi dari berbagai museum dan perpustakaan didigitalisasi.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-06-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 2-5',
    kataKunci: ['manuskrip', 'digitalisasi', 'Nusantara', 'budaya'],
    lokasiKoleksi: 'Arsip Koran Jun 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '41',
    judul: 'Podcast Literasi Raih Pendengar Jutaan',
    pengarang: 'Faisal Rahman',
    subjek: ['Literasi Digital', 'Teknologi Informasi', 'Seni & Sastra'],
    abstrak: 'Podcast bertema literasi berhasil meraih jutaan pendengar dalam waktu singkat. Format audio ini menjadi alternatif menarik untuk mempromosikan budaya baca.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-06-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 1-4',
    kataKunci: ['podcast', 'literasi', 'audio', 'digital'],
    lokasiKoleksi: 'Arsip Koran Jun 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '42',
    judul: 'Perpustakaan Apung Layani Nelayan Pesisir',
    pengarang: 'Hadi Susanto',
    subjek: ['Pustakawan & Perpustakaan', 'Sosial Politik'],
    abstrak: 'Perpustakaan apung hadir untuk melayani komunitas nelayan di pesisir yang selama ini sulit menjangkau perpustakaan darat. Koleksi disesuaikan dengan kebutuhan warga.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-06-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 2-4',
    kataKunci: ['perpustakaan apung', 'nelayan', 'pesisir', 'layanan'],
    lokasiKoleksi: 'Arsip Koran Jun 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '43',
    judul: 'Workshop Ilustrasi Buku Anak',
    pengarang: 'Maya Kartini',
    subjek: ['Seni & Sastra', 'Literasi Anak'],
    abstrak: 'Workshop ilustrasi buku anak menghadirkan ilustrator profesional sebagai narasumber. Peserta belajar teknik menggambar yang menarik untuk buku cerita anak.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 1-3',
    kataKunci: ['ilustrasi', 'buku anak', 'workshop', 'seni'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingDesainGrafis1,
  },
  {
    id: '44',
    judul: 'Seminar Hak Cipta dalam Penerbitan Buku',
    pengarang: 'Dr. Hukum Aditya',
    subjek: ['Ekonomi & Bisnis', 'Sosial Politik'],
    abstrak: 'Seminar tentang hak cipta dalam penerbitan buku digelar untuk memberikan pemahaman kepada penulis dan penerbit. Materi mencakup aspek legal dalam industri penerbitan.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 2-5',
    kataKunci: ['hak cipta', 'penerbitan', 'legal', 'penulis'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '45',
    judul: 'Literasi Media untuk Jurnalis Muda',
    pengarang: 'Eka Saputra',
    subjek: ['Literasi Digital', 'Pendidikan', 'Sosial Politik'],
    abstrak: 'Pelatihan literasi media untuk jurnalis muda bertujuan meningkatkan kualitas jurnalisme. Peserta belajar etika jurnalistik dan cara memverifikasi informasi.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-4',
    kataKunci: ['literasi media', 'jurnalis', 'etika', 'verifikasi'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '46',
    judul: 'Gerakan 1000 Buku untuk Indonesia Timur',
    pengarang: 'Yohanes Wenas',
    subjek: ['Pendidikan', 'Sosial Politik'],
    abstrak: 'Gerakan 1000 Buku berhasil mengumpulkan dan mendistribusikan ribuan buku ke wilayah Indonesia Timur. Kegiatan ini melibatkan berbagai komunitas dan relawan.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 2-4',
    kataKunci: ['gerakan buku', 'Indonesia Timur', 'donasi', 'relawan'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '47',
    judul: 'Temu Penulis Perempuan Indonesia',
    pengarang: 'Ratna Sari Dewi',
    subjek: ['Seni & Sastra', 'Sosial Politik'],
    abstrak: 'Temu penulis perempuan Indonesia menghadirkan puluhan penulis wanita berbakat. Acara ini menjadi wadah untuk berbagi pengalaman dan jaringan di dunia literasi.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 1-4',
    kataKunci: ['penulis perempuan', 'sastra', 'komunitas', 'literasi'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '48',
    judul: 'Literasi Kesehatan Mental Melalui Buku',
    pengarang: 'dr. Ananda Putri',
    subjek: ['Kesehatan', 'Pendidikan'],
    abstrak: 'Program literasi kesehatan mental menggunakan buku sebagai media untuk meningkatkan kesadaran masyarakat. Koleksi buku bertema psikologi dan kesehatan mental dipromosikan.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-30',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 2-5',
    kataKunci: ['kesehatan mental', 'literasi', 'psikologi', 'buku'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '49',
    judul: 'Perpustakaan Taman Menjadi Destinasi Wisata Edukasi',
    pengarang: 'Denny Kurniawan',
    subjek: ['Pustakawan & Perpustakaan', 'Bahasa & Budaya'],
    abstrak: 'Perpustakaan taman yang didesain unik menjadi destinasi wisata edukasi baru. Pengunjung dapat menikmati suasana alam sambil membaca dan belajar.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-3',
    kataKunci: ['perpustakaan taman', 'wisata edukasi', 'alam', 'baca'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
    fotoUrl: klipingDesainGrafis3,
  },
  {
    id: '50',
    judul: 'Festival Puisi Nasional 2024 Digelar Meriah',
    pengarang: 'Teguh Prasetya',
    subjek: ['Seni & Sastra', 'Bahasa & Budaya'],
    abstrak: 'Festival Puisi Nasional 2024 digelar dengan berbagai rangkaian kegiatan. Penyair dari berbagai daerah berkumpul untuk merayakan karya sastra Indonesia.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 2-4',
    kataKunci: ['festival puisi', 'sastra', 'penyair', 'nasional'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '51',
    judul: 'Literasi Tanggap Bencana untuk Masyarakat',
    pengarang: 'Ardi Wijaya',
    subjek: ['Sosial Politik', 'Kesehatan', 'Pendidikan'],
    abstrak: 'Program literasi tanggap bencana mengajarkan masyarakat cara menghadapi situasi darurat. Buku panduan dan simulasi menjadi bagian dari kegiatan edukasi.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 1-4',
    kataKunci: ['bencana', 'literasi', 'tanggap darurat', 'edukasi'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '52',
    judul: 'Kelas Menulis Online Raih Ribuan Peserta',
    pengarang: 'Nadia Safitri',
    subjek: ['Literasi Digital', 'Pendidikan', 'Seni & Sastra'],
    abstrak: 'Kelas menulis online berhasil menarik ribuan peserta dari berbagai daerah. Platform digital memungkinkan pembelajaran jarak jauh yang efektif dan terjangkau.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 2-5',
    kataKunci: ['kelas online', 'menulis', 'digital', 'pembelajaran'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '53',
    judul: 'Perpustakaan Sekolah Model Diresmikan',
    pengarang: 'Irwan Setiadi',
    subjek: ['Pustakawan & Perpustakaan', 'Pendidikan'],
    abstrak: 'Perpustakaan sekolah model dengan fasilitas lengkap resmi diresmikan. Konsep modern dan koleksi yang kaya diharapkan menjadi contoh bagi sekolah lain.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 1-3',
    kataKunci: ['perpustakaan sekolah', 'model', 'fasilitas', 'modern'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '54',
    judul: 'Talkshow Literasi Bersama Tokoh Nasional',
    pengarang: 'Gilang Permana',
    subjek: ['Bahasa & Budaya', 'Sosial Politik'],
    abstrak: 'Talkshow literasi menghadirkan tokoh nasional sebagai narasumber. Diskusi hangat tentang pentingnya budaya baca dalam membangun bangsa menarik perhatian publik.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 2-4',
    kataKunci: ['talkshow', 'literasi', 'tokoh nasional', 'budaya baca'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '55',
    judul: 'Pelatihan Storytelling untuk Orang Tua',
    pengarang: 'Wulan Maharani',
    subjek: ['Literasi Anak', 'Pendidikan'],
    abstrak: 'Pelatihan storytelling untuk orang tua bertujuan meningkatkan kemampuan mendongeng kepada anak. Teknik menarik perhatian anak melalui cerita diajarkan oleh para ahli.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 1-4',
    kataKunci: ['storytelling', 'orang tua', 'dongeng', 'anak'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '56',
    judul: 'Buku Digital Ramah Lingkungan',
    pengarang: 'Taufik Hidayat',
    subjek: ['Literasi Digital', 'Teknologi Informasi'],
    abstrak: 'Kampanye buku digital sebagai alternatif ramah lingkungan semakin gencar. E-book dinilai dapat mengurangi penggunaan kertas dan melestarikan hutan.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 2-5',
    kataKunci: ['buku digital', 'lingkungan', 'e-book', 'konservasi'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '57',
    judul: 'Komunitas Penulis Indie Berkembang Pesat',
    pengarang: 'Sandra Dewi',
    subjek: ['Seni & Sastra', 'Ekonomi & Bisnis'],
    abstrak: 'Komunitas penulis indie menunjukkan perkembangan pesat dengan banyaknya karya yang dipublikasikan secara mandiri. Platform self-publishing menjadi pilihan populer.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-3',
    kataKunci: ['penulis indie', 'self-publishing', 'komunitas', 'karya'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingDesainGrafis1,
  },
  {
    id: '58',
    judul: 'Literasi Kritis untuk Generasi Muda',
    pengarang: 'Dr. Suharto',
    subjek: ['Pendidikan', 'Literasi Digital', 'Sosial Politik'],
    abstrak: 'Program literasi kritis untuk generasi muda mengajarkan cara menganalisis informasi secara mendalam. Kemampuan berpikir kritis menjadi fokus utama pembelajaran.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 2-4',
    kataKunci: ['literasi kritis', 'generasi muda', 'berpikir kritis', 'analisis'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '59',
    judul: 'Pameran Foto Sejarah Literasi Indonesia',
    pengarang: 'Budiman Arif',
    subjek: ['Bahasa & Budaya', 'Seni & Sastra'],
    abstrak: 'Pameran foto sejarah literasi Indonesia menghadirkan dokumentasi perkembangan dunia buku dan perpustakaan dari masa ke masa. Koleksi langka dipamerkan untuk publik.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 1-4',
    kataKunci: ['pameran foto', 'sejarah', 'literasi', 'dokumentasi'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '60',
    judul: 'Bimbingan Teknis Pengelolaan Perpustakaan Desa',
    pengarang: 'Ibu Sumarni',
    subjek: ['Pustakawan & Perpustakaan', 'Pendidikan'],
    abstrak: 'Bimbingan teknis pengelolaan perpustakaan desa diselenggarakan untuk meningkatkan kapasitas pengelola. Materi mencakup katalogisasi, pelayanan, dan promosi.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 2-5',
    kataKunci: ['bimbingan teknis', 'perpustakaan desa', 'pengelolaan', 'kapasitas'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingDesainGrafis3,
  },
  {
    id: '61',
    judul: 'Launching Buku Biografi Tokoh Literasi',
    pengarang: 'Hermawan Kertajaya',
    subjek: ['Seni & Sastra', 'Bahasa & Budaya'],
    abstrak: 'Peluncuran buku biografi tokoh literasi Indonesia dihadiri ratusan tamu undangan. Buku ini mendokumentasikan perjalanan hidup dan kontribusi tokoh dalam dunia literasi.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-30',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 16, Kol. 1-3',
    kataKunci: ['biografi', 'tokoh literasi', 'peluncuran buku', 'dokumentasi'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '62',
    judul: 'Literasi Pertanian untuk Petani Modern',
    pengarang: 'Ir. Gunawan',
    subjek: ['Ekonomi & Bisnis', 'Teknologi Informasi'],
    abstrak: 'Program literasi pertanian mengajarkan teknik bertani modern kepada petani. Buku panduan dan aplikasi menjadi media pembelajaran yang efektif.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 2-4',
    kataKunci: ['literasi pertanian', 'petani modern', 'teknologi', 'panduan'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '63',
    judul: 'Kompetisi Desain Sampul Buku Kreatif',
    pengarang: 'Vania Putri',
    subjek: ['Seni & Sastra', 'Ekonomi & Bisnis'],
    abstrak: 'Kompetisi desain sampul buku kreatif menarik minat ratusan desainer muda. Karya terbaik akan digunakan untuk penerbitan buku-buku mendatang.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 1-4',
    kataKunci: ['desain sampul', 'kompetisi', 'kreatif', 'desainer'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '64',
    judul: 'Literasi Hukum untuk Masyarakat Awam',
    pengarang: 'Dr. Hukum Pratama',
    subjek: ['Sosial Politik', 'Pendidikan'],
    abstrak: 'Program literasi hukum memberikan pemahaman dasar tentang hukum kepada masyarakat. Materi disederhanakan agar mudah dipahami oleh orang awam.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 2-5',
    kataKunci: ['literasi hukum', 'masyarakat', 'pemahaman', 'edukasi'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '65',
    judul: 'Perpustakaan Hijau dengan Konsep Eco-Friendly',
    pengarang: 'Arsitek Budi',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi'],
    abstrak: 'Perpustakaan dengan konsep ramah lingkungan diresmikan. Bangunan menggunakan material daur ulang dan energi terbarukan untuk operasionalnya.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 1-3',
    kataKunci: ['perpustakaan hijau', 'eco-friendly', 'lingkungan', 'arsitektur'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '66',
    judul: 'Reading Challenge Nasional Raih Antusiasme Tinggi',
    pengarang: 'Putri Lestari',
    subjek: ['Bahasa & Budaya', 'Literasi Digital'],
    abstrak: 'Tantangan membaca nasional berhasil menarik partisipasi jutaan pembaca. Program ini mendorong masyarakat untuk menargetkan jumlah buku yang dibaca dalam setahun.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 2-4',
    kataKunci: ['reading challenge', 'tantangan membaca', 'partisipasi', 'nasional'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '67',
    judul: 'Workshop Penerjemahan Buku Asing',
    pengarang: 'Dr. Linguistik Dewi',
    subjek: ['Bahasa & Budaya', 'Pendidikan'],
    abstrak: 'Workshop penerjemahan buku asing mengajarkan teknik dan etika dalam menerjemahkan karya sastra. Peserta belajar dari penerjemah profesional berpengalaman.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 1-4',
    kataKunci: ['penerjemahan', 'buku asing', 'workshop', 'bahasa'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '68',
    judul: 'Literasi Ekonomi Kreatif di Era Digital',
    pengarang: 'Ekonom Susilo',
    subjek: ['Ekonomi & Bisnis', 'Literasi Digital'],
    abstrak: 'Program literasi ekonomi kreatif membekali pelaku usaha dengan pengetahuan bisnis di era digital. Strategi pemasaran online dan branding menjadi fokus utama.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-30',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 2-5',
    kataKunci: ['ekonomi kreatif', 'digital', 'pemasaran', 'bisnis'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingDesainGrafis1,
  },
  {
    id: '69',
    judul: 'Bulan Bahasa dan Sastra Indonesia 2024',
    pengarang: 'Tim Redaksi',
    subjek: ['Bahasa & Budaya', 'Seni & Sastra'],
    abstrak: 'Peringatan Bulan Bahasa dan Sastra Indonesia digelar dengan berbagai kegiatan. Seminar, lomba, dan pameran memeriahkan perayaan ini.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-28',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-4',
    kataKunci: ['Bulan Bahasa', 'sastra Indonesia', 'perayaan', 'kegiatan'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '70',
    judul: 'Perpustakaan Komunitas Hadir di Kawasan Kumuh',
    pengarang: 'Aktivis Heri',
    subjek: ['Pustakawan & Perpustakaan', 'Sosial Politik'],
    abstrak: 'Perpustakaan komunitas didirikan di kawasan kumuh untuk memberikan akses literasi kepada warga. Buku dan kegiatan belajar rutin diselenggarakan.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 1-3',
    kataKunci: ['perpustakaan komunitas', 'kawasan kumuh', 'akses literasi', 'sosial'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '71',
    judul: 'Teknologi AI dalam Pengembangan Perpustakaan',
    pengarang: 'Tech Expert Rudi',
    subjek: ['Teknologi Informasi', 'Pustakawan & Perpustakaan'],
    abstrak: 'Penerapan teknologi AI dalam perpustakaan mulai dikembangkan untuk meningkatkan layanan. Chatbot dan rekomendasi buku otomatis menjadi fitur unggulan.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 2-4',
    kataKunci: ['AI', 'perpustakaan', 'teknologi', 'layanan'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '72',
    judul: 'Gerakan Literasi Berbasis Masjid',
    pengarang: 'Ustaz Ahmad',
    subjek: ['Bahasa & Budaya', 'Sosial Politik', 'Pendidikan'],
    abstrak: 'Gerakan literasi berbasis masjid mengintegrasikan kegiatan membaca dengan pendidikan agama. Pojok baca di masjid mulai banyak didirikan.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 1-4',
    kataKunci: ['literasi masjid', 'agama', 'pojok baca', 'komunitas'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '73',
    judul: 'Hari Pahlawan Diperingati dengan Literasi Sejarah',
    pengarang: 'Sejarawan Nugroho',
    subjek: ['Bahasa & Budaya', 'Pendidikan', 'Sosial Politik'],
    abstrak: 'Peringatan Hari Pahlawan dikemas dengan kegiatan literasi sejarah. Bedah buku biografi pahlawan dan diskusi sejarah perjuangan menjadi acara utama.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-5',
    kataKunci: ['Hari Pahlawan', 'literasi sejarah', 'biografi', 'perjuangan'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '74',
    judul: 'Literasi Kelautan untuk Generasi Pesisir',
    pengarang: 'Maritim Joko',
    subjek: ['Pendidikan', 'Bahasa & Budaya'],
    abstrak: 'Program literasi kelautan hadir untuk generasi muda di daerah pesisir. Pengetahuan tentang laut dan maritim diajarkan melalui buku dan kegiatan lapangan.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 2-4',
    kataKunci: ['literasi kelautan', 'pesisir', 'maritim', 'generasi muda'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '75',
    judul: 'Penghargaan Perpustakaan Terbaik 2024',
    pengarang: 'Tim Juri Nasional',
    subjek: ['Pustakawan & Perpustakaan', 'Pendidikan'],
    abstrak: 'Penghargaan perpustakaan terbaik 2024 diberikan kepada perpustakaan yang berhasil meningkatkan layanan dan inovasi. Berbagai kategori diberikan kepada pemenang.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-3',
    kataKunci: ['penghargaan', 'perpustakaan terbaik', 'inovasi', 'layanan'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingDesainGrafis3,
  },
  {
    id: '76',
    judul: 'Bazar Buku Bekas untuk Literasi',
    pengarang: 'Koordinator Ani',
    subjek: ['Ekonomi & Bisnis', 'Sosial Politik'],
    abstrak: 'Bazar buku bekas digelar untuk menyediakan buku murah bagi masyarakat. Dana hasil penjualan disumbangkan untuk pengembangan perpustakaan daerah.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 2-5',
    kataKunci: ['bazar buku', 'bekas', 'murah', 'donasi'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '77',
    judul: 'Literasi Visual untuk Siswa Tunarungu',
    pengarang: 'Pendidik Khusus Dewi',
    subjek: ['Pendidikan', 'Kesehatan', 'Seni & Sastra'],
    abstrak: 'Program literasi visual dikembangkan untuk siswa tunarungu. Buku bergambar dan video bahasa isyarat menjadi media pembelajaran utama.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-28',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-4',
    kataKunci: ['literasi visual', 'tunarungu', 'bahasa isyarat', 'inklusif'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '78',
    judul: 'Kolaborasi Penerbit dan Perpustakaan untuk Akses Buku',
    pengarang: 'Direktur Penerbit',
    subjek: ['Pustakawan & Perpustakaan', 'Ekonomi & Bisnis'],
    abstrak: 'Kolaborasi antara penerbit dan perpustakaan dilakukan untuk memperluas akses buku kepada masyarakat. Program diskon dan donasi buku menjadi fokus kerja sama.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-01',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 2-4',
    kataKunci: ['kolaborasi', 'penerbit', 'perpustakaan', 'akses buku'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '79',
    judul: 'Gerakan Baca Sepanjang Hayat',
    pengarang: 'Tokoh Pendidikan',
    subjek: ['Pendidikan', 'Bahasa & Budaya'],
    abstrak: 'Gerakan baca sepanjang hayat dikampanyekan untuk mendorong masyarakat terus membaca di segala usia. Program lintas generasi dikembangkan untuk mendukung gerakan ini.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 1-3',
    kataKunci: ['baca sepanjang hayat', 'lintas generasi', 'kampanye', 'membaca'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '80',
    judul: 'Seminar Internasional Perpustakaan dan Informasi',
    pengarang: 'Panitia Seminar',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi'],
    abstrak: 'Seminar internasional perpustakaan dan informasi menghadirkan pembicara dari berbagai negara. Isu terkini tentang pengembangan perpustakaan dibahas secara mendalam.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-08',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 2-5',
    kataKunci: ['seminar internasional', 'perpustakaan', 'informasi', 'global'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '81',
    judul: 'Literasi Nutrisi untuk Ibu Hamil dan Menyusui',
    pengarang: 'dr. Gizi Pratiwi',
    subjek: ['Kesehatan', 'Pendidikan'],
    abstrak: 'Program literasi nutrisi memberikan edukasi tentang gizi seimbang untuk ibu hamil dan menyusui. Buku panduan dan kelas interaktif menjadi media pembelajaran.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-10',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 7, Kol. 1-4',
    kataKunci: ['literasi nutrisi', 'ibu hamil', 'gizi', 'kesehatan'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '82',
    judul: 'Buku Panduan UMKM Diluncurkan',
    pengarang: 'Kemenkop UKM',
    subjek: ['Ekonomi & Bisnis', 'Pendidikan'],
    abstrak: 'Buku panduan untuk pelaku UMKM resmi diluncurkan. Buku ini berisi strategi bisnis, pemasaran digital, dan pengelolaan keuangan untuk usaha kecil menengah.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-12',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 2-4',
    kataKunci: ['UMKM', 'panduan', 'bisnis', 'pemasaran'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '83',
    judul: 'Festival Buku Anak Indonesia 2024',
    pengarang: 'Panitia Festival',
    subjek: ['Literasi Anak', 'Seni & Sastra'],
    abstrak: 'Festival Buku Anak Indonesia 2024 digelar meriah dengan berbagai kegiatan menarik. Pameran, workshop, dan pertunjukan menjadi daya tarik bagi anak-anak.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-14',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-4',
    kataKunci: ['festival buku anak', 'pameran', 'workshop', 'literasi anak'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '84',
    judul: 'Tahun Baru Literasi: Resolusi Membaca 2025',
    pengarang: 'Komunitas Baca',
    subjek: ['Bahasa & Budaya', 'Sosial Politik'],
    abstrak: 'Menjelang tahun baru, kampanye resolusi membaca 2025 diluncurkan. Masyarakat diajak untuk membuat target membaca sebagai bagian dari resolusi tahun baru.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-28',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 2-5',
    kataKunci: ['resolusi', 'membaca', 'tahun baru', 'target'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '85',
    judul: 'Perpustakaan Digital Nasional Capai 10 Juta Pengguna',
    pengarang: 'Tim Perpusnas',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi', 'Literasi Digital'],
    abstrak: 'Perpustakaan Digital Nasional berhasil mencapai 10 juta pengguna terdaftar. Pencapaian ini menunjukkan meningkatnya minat masyarakat terhadap literasi digital.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-15',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-4',
    kataKunci: ['perpustakaan digital', 'pengguna', 'nasional', 'literasi digital'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingDesainGrafis1,
  },
  {
    id: '86',
    judul: 'Lokakarya Penerbitan Buku Indie',
    pengarang: 'Penerbit Indie Raka',
    subjek: ['Seni & Sastra', 'Ekonomi & Bisnis'],
    abstrak: 'Lokakarya penerbitan buku indie mengajarkan proses publikasi mandiri kepada penulis pemula. Peserta belajar dari tahap penulisan hingga pemasaran.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-18',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-3',
    kataKunci: ['penerbitan indie', 'lokakarya', 'penulis pemula', 'self-publishing'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '87',
    judul: 'Literasi Keuangan Digital untuk Milenial',
    pengarang: 'Fintech Expert Maya',
    subjek: ['Ekonomi & Bisnis', 'Literasi Digital', 'Teknologi Informasi'],
    abstrak: 'Program literasi keuangan digital ditargetkan untuk generasi milenial. Materi mencakup investasi online, fintech, dan pengelolaan keuangan berbasis aplikasi.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-20',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 2-5',
    kataKunci: ['literasi keuangan', 'digital', 'milenial', 'fintech'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '88',
    judul: 'Refleksi Akhir Tahun: Capaian Literasi Nasional 2024',
    pengarang: 'Analis Kebijakan',
    subjek: ['Sosial Politik', 'Pendidikan'],
    abstrak: 'Refleksi akhir tahun menyajikan capaian literasi nasional sepanjang 2024. Data dan analisis menunjukkan perkembangan positif di berbagai indikator literasi.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-30',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 6, Kol. 1-4',
    kataKunci: ['refleksi', 'capaian', 'literasi nasional', '2024'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '89',
    judul: 'Perpustakaan Kafe: Trend Baru Ruang Baca',
    pengarang: 'Lifestyle Writer',
    subjek: ['Pustakawan & Perpustakaan', 'Ekonomi & Bisnis'],
    abstrak: 'Konsep perpustakaan kafe menjadi trend baru di kalangan anak muda. Kombinasi suasana kafe yang nyaman dengan koleksi buku menarik banyak pengunjung.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-22',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 16, Kol. 1-4',
    kataKunci: ['perpustakaan kafe', 'trend', 'ruang baca', 'anak muda'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '90',
    judul: 'Peran Perpustakaan dalam Pelestarian Budaya Lokal',
    pengarang: 'Budayawan Kusno',
    subjek: ['Bahasa & Budaya', 'Pustakawan & Perpustakaan'],
    abstrak: 'Perpustakaan memiliki peran penting dalam pelestarian budaya lokal. Koleksi tentang tradisi, bahasa daerah, dan kesenian lokal terus dikembangkan dan dipromosikan.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-25',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 2-4',
    kataKunci: ['pelestarian', 'budaya lokal', 'perpustakaan', 'tradisi'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '91',
    judul: 'Literasi Teknologi untuk Guru SD',
    pengarang: 'Dinas Pendidikan',
    subjek: ['Pendidikan', 'Teknologi Informasi', 'Literasi Digital'],
    abstrak: 'Program literasi teknologi untuk guru SD bertujuan meningkatkan kemampuan mengajar dengan media digital. Pelatihan mencakup pembuatan konten pembelajaran interaktif.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-12',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 8, Kol. 1-3',
    kataKunci: ['literasi teknologi', 'guru SD', 'media digital', 'pembelajaran'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
    fotoUrl: klipingDesainGrafis3,
  },
  {
    id: '92',
    judul: 'Kompetisi Resensi Buku Online',
    pengarang: 'Platform Literasi',
    subjek: ['Seni & Sastra', 'Literasi Digital'],
    abstrak: 'Kompetisi resensi buku online digelar untuk mendorong aktivitas menulis dan membaca. Peserta mengunggah resensi di platform digital dan dinilai oleh juri.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-03-08',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 2-4',
    kataKunci: ['resensi buku', 'kompetisi online', 'menulis', 'digital'],
    lokasiKoleksi: 'Arsip Koran Mar 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '93',
    judul: 'Kelas Fotografi Dokumentasi Literasi',
    pengarang: 'Fotografer Adi',
    subjek: ['Seni & Sastra', 'Teknologi Informasi'],
    abstrak: 'Kelas fotografi dokumentasi literasi mengajarkan teknik memotret kegiatan membaca dan perpustakaan. Peserta belajar menangkap momen literasi yang inspiring.',
    namaMedia: 'Kedaulatan Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-04-22',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 14, Kol. 1-3',
    kataKunci: ['fotografi', 'dokumentasi', 'literasi', 'perpustakaan'],
    lokasiKoleksi: 'Arsip Koran Apr 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
  {
    id: '94',
    judul: 'Gerakan Wakaf Buku Nasional',
    pengarang: 'Yayasan Literasi',
    subjek: ['Sosial Politik', 'Bahasa & Budaya'],
    abstrak: 'Gerakan wakaf buku nasional mengajak masyarakat menyumbangkan buku untuk perpustakaan. Program ini bertujuan memperkaya koleksi perpustakaan di seluruh Indonesia.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-05-02',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 9, Kol. 2-5',
    kataKunci: ['wakaf buku', 'donasi', 'perpustakaan', 'nasional'],
    lokasiKoleksi: 'Arsip Koran Mei 2024',
    fotoUrl: klipingVlogging,
  },
  {
    id: '95',
    judul: 'Literasi Olahraga untuk Atlet Muda',
    pengarang: 'Pelatih Nasional',
    subjek: ['Kesehatan', 'Pendidikan'],
    abstrak: 'Program literasi olahraga memberikan pengetahuan tentang teknik, nutrisi, dan mental kepada atlet muda. Buku panduan olahraga menjadi sumber belajar utama.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-06-08',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-4',
    kataKunci: ['literasi olahraga', 'atlet muda', 'nutrisi', 'mental'],
    lokasiKoleksi: 'Arsip Koran Jun 2024',
    fotoUrl: klipingKekuasaanBahasa,
  },
  {
    id: '96',
    judul: 'Perpustakaan Berbasis Augmented Reality',
    pengarang: 'Tech Innovator',
    subjek: ['Teknologi Informasi', 'Pustakawan & Perpustakaan'],
    abstrak: 'Perpustakaan dengan teknologi augmented reality mulai dikembangkan. Pengunjung dapat mengakses informasi tambahan tentang buku melalui aplikasi AR di smartphone.',
    namaMedia: 'Jawa Pos',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-07-12',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 10, Kol. 2-4',
    kataKunci: ['augmented reality', 'perpustakaan', 'teknologi', 'inovasi'],
    lokasiKoleksi: 'Arsip Koran Jul 2024',
    fotoUrl: klipingMinatBaca,
  },
  {
    id: '97',
    judul: 'Literasi Musik Tradisional Indonesia',
    pengarang: 'Musisi Tradisional',
    subjek: ['Seni & Sastra', 'Bahasa & Budaya'],
    abstrak: 'Program literasi musik tradisional mengajarkan sejarah dan cara memainkan alat musik tradisional Indonesia. Buku dan video tutorial menjadi media pembelajaran.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-18',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 11, Kol. 1-3',
    kataKunci: ['musik tradisional', 'literasi', 'budaya', 'alat musik'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
    fotoUrl: klipingWastraNusantara,
  },
  {
    id: '98',
    judul: 'Perpustakaan Ramah Anak dengan Ruang Bermain',
    pengarang: 'Arsitek Anak',
    subjek: ['Literasi Anak', 'Pustakawan & Perpustakaan'],
    abstrak: 'Perpustakaan ramah anak dengan fasilitas ruang bermain diresmikan. Desain menarik dan koleksi buku anak yang lengkap menjadi daya tarik utama.',
    namaMedia: 'Suara Merdeka',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-09-08',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 13, Kol. 2-5',
    kataKunci: ['perpustakaan anak', 'ruang bermain', 'ramah anak', 'desain'],
    lokasiKoleksi: 'Arsip Koran Sep 2024',
    fotoUrl: klipingBordir,
  },
  {
    id: '99',
    judul: 'Seminar Literasi Multibahasa untuk Diplomat',
    pengarang: 'Kemenlu RI',
    subjek: ['Bahasa & Budaya', 'Pendidikan', 'Sosial Politik'],
    abstrak: 'Seminar literasi multibahasa diselenggarakan untuk meningkatkan kemampuan diplomat Indonesia. Penguasaan berbagai bahasa menjadi kompetensi penting dalam diplomasi.',
    namaMedia: 'Pikiran Rakyat',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-10-08',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 6, Kol. 1-4',
    kataKunci: ['multibahasa', 'diplomat', 'literasi', 'diplomasi'],
    lokasiKoleksi: 'Arsip Koran Okt 2024',
    fotoUrl: klipingDesainGrafis2,
  },
  {
    id: '100',
    judul: 'Akhir Tahun: Rekomendasi Buku Terbaik 2024',
    pengarang: 'Kritikus Sastra',
    subjek: ['Seni & Sastra', 'Bahasa & Budaya'],
    abstrak: 'Daftar rekomendasi buku terbaik 2024 dirilis oleh para kritikus sastra. Berbagai genre dan penulis masuk dalam daftar bacaan wajib akhir tahun.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-12-31',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-5',
    kataKunci: ['rekomendasi buku', 'terbaik 2024', 'bacaan', 'sastra'],
    lokasiKoleksi: 'Arsip Koran Des 2024',
    fotoUrl: klipingPelatihanMenulis,
  },
];

export const statistics = {
  totalArticles: 100,
  totalMedia: 10,
  yearRange: { start: 2024, end: 2024 },
  categories: {
    koran: 100,
    jurnal: 0,
    majalah: 0,
    buletin: 0,
  },
};

export const getPublicationTypeLabel = (type: JenisTerbitan): string => {
  const labels: Record<JenisTerbitan, string> = {
    koran: 'Surat Kabar',
    jurnal: 'Jurnal Ilmiah',
    majalah: 'Majalah',
    buletin: 'Buletin',
  };
  return labels[type];
};

export const getPublicationTypeColor = (type: JenisTerbitan): string => {
  const colors: Record<JenisTerbitan, string> = {
    koran: 'bg-orange-500',
    jurnal: 'bg-blue-500',
    majalah: 'bg-purple-500',
    buletin: 'bg-emerald-500',
  };
  return colors[type];
};
