export type JenisTerbitan = 'koran' | 'jurnal' | 'majalah' | 'buletin';

export interface Article {
  id: string;
  judul: string;
  pengarang: string;
  subjek: string[];
  abstrak: string;
  namaMedia: string;
  jenisTerbitan: JenisTerbitan;
  volume?: string;
  nomor?: string;
  tanggalTerbit: string;
  tahunTerbit: number;
  halamanKolom: string;
  kataKunci: string[];
  lokasiKoleksi: string;
  issn?: string;
}

export const subjects = [
  'Literasi Digital',
  'Literasi Anak',
  'Pustakawan & Perpustakaan',
  'Bahasa & Budaya',
  'Pendidikan',
  'Teknologi Informasi',
  'Ekonomi & Bisnis',
  'Kesehatan',
  'Sosial Politik',
  'Seni & Sastra',
];

export const mediaList = [
  { nama: 'Kompas', jenis: 'koran' as JenisTerbitan },
  { nama: 'Tempo', jenis: 'majalah' as JenisTerbitan },
  { nama: 'Jurnal Perpustakaan', jenis: 'jurnal' as JenisTerbitan },
  { nama: 'Media Indonesia', jenis: 'koran' as JenisTerbitan },
  { nama: 'Republika', jenis: 'koran' as JenisTerbitan },
  { nama: 'Intisari', jenis: 'majalah' as JenisTerbitan },
  { nama: 'Visi Pustaka', jenis: 'jurnal' as JenisTerbitan },
  { nama: 'Buletin Perpusnas', jenis: 'buletin' as JenisTerbitan },
  { nama: 'Khazanah Pustaka', jenis: 'jurnal' as JenisTerbitan },
  { nama: 'Warta Pustakawan', jenis: 'buletin' as JenisTerbitan },
];

export const sampleArticles: Article[] = [
  {
    id: '1',
    judul: 'Transformasi Perpustakaan Digital di Era Society 5.0',
    pengarang: 'Dr. Sari Dewi Kusumawati',
    subjek: ['Literasi Digital', 'Pustakawan & Perpustakaan'],
    abstrak: 'Artikel ini membahas bagaimana perpustakaan bertransformasi menghadapi era Society 5.0, di mana integrasi teknologi dan kemanusiaan menjadi kunci. Pembahasan mencakup strategi digitalisasi koleksi, pengembangan layanan berbasis AI, serta peran pustakawan sebagai navigator informasi di era baru.',
    namaMedia: 'Visi Pustaka',
    jenisTerbitan: 'jurnal',
    volume: '24',
    nomor: '2',
    tanggalTerbit: '2024-06-15',
    tahunTerbit: 2024,
    halamanKolom: '45-58',
    kataKunci: ['perpustakaan digital', 'Society 5.0', 'transformasi', 'teknologi'],
    lokasiKoleksi: 'Rak Jurnal A-12',
    issn: '1411-0199',
  },
  {
    id: '2',
    judul: 'Membangun Kebiasaan Membaca Sejak Dini: Peran Orang Tua dan Perpustakaan',
    pengarang: 'Ratna Megawati, M.Pd.',
    subjek: ['Literasi Anak', 'Pendidikan'],
    abstrak: 'Penelitian ini mengkaji pentingnya kolaborasi antara orang tua dan perpustakaan dalam membangun kebiasaan membaca anak usia dini. Hasil penelitian menunjukkan bahwa program read-aloud dan storytelling efektif meningkatkan minat baca anak usia 3-6 tahun.',
    namaMedia: 'Jurnal Perpustakaan',
    jenisTerbitan: 'jurnal',
    volume: '12',
    nomor: '1',
    tanggalTerbit: '2024-03-20',
    tahunTerbit: 2024,
    halamanKolom: '12-28',
    kataKunci: ['literasi anak', 'minat baca', 'read-aloud', 'perpustakaan anak'],
    lokasiKoleksi: 'Rak Jurnal B-05',
    issn: '2089-3612',
  },
  {
    id: '3',
    judul: 'Kecerdasan Buatan Mengubah Wajah Layanan Perpustakaan',
    pengarang: 'Ahmad Fauzi',
    subjek: ['Teknologi Informasi', 'Pustakawan & Perpustakaan'],
    abstrak: 'Liputan mendalam tentang penerapan kecerdasan buatan (AI) di berbagai perpustakaan di Indonesia. Beberapa perpustakaan telah mengimplementasikan chatbot untuk layanan referensi 24 jam dan sistem rekomendasi buku berbasis machine learning.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-11-05',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 6, Kol. 3-5',
    kataKunci: ['AI', 'kecerdasan buatan', 'perpustakaan', 'inovasi'],
    lokasiKoleksi: 'Arsip Koran Nov 2024',
  },
  {
    id: '4',
    judul: 'Pelestarian Naskah Kuno Nusantara: Tantangan dan Harapan',
    pengarang: 'Prof. Dr. Bambang Suryanto',
    subjek: ['Bahasa & Budaya', 'Pustakawan & Perpustakaan'],
    abstrak: 'Artikel mengulas upaya pelestarian naskah kuno Nusantara yang tersebar di berbagai perpustakaan dan museum. Pembahasan mencakup teknik konservasi tradisional dan modern, serta pentingnya digitalisasi untuk menjaga aksesibilitas warisan budaya bangsa.',
    namaMedia: 'Tempo',
    jenisTerbitan: 'majalah',
    tanggalTerbit: '2024-09-10',
    tahunTerbit: 2024,
    halamanKolom: '78-82',
    kataKunci: ['naskah kuno', 'pelestarian', 'konservasi', 'digitalisasi', 'budaya'],
    lokasiKoleksi: 'Rak Majalah C-08',
  },
  {
    id: '5',
    judul: 'Perpustakaan Keliling: Menjangkau Pelosok Negeri',
    pengarang: 'Dewi Anggraini',
    subjek: ['Pustakawan & Perpustakaan', 'Pendidikan'],
    abstrak: 'Laporan khusus tentang program perpustakaan keliling yang berhasil meningkatkan literasi di daerah terpencil. Kisah inspiratif para pustakawan yang berjuang membawa buku ke pedalaman Kalimantan dan Papua.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-17',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 12, Kol. 1-4',
    kataKunci: ['perpustakaan keliling', 'literasi', 'daerah terpencil', 'inklusi'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
  },
  {
    id: '6',
    judul: 'Kompetensi Pustakawan Milenial: Antara Tradisi dan Modernitas',
    pengarang: 'Rina Fitriani, M.IP.',
    subjek: ['Pustakawan & Perpustakaan'],
    abstrak: 'Kajian tentang kompetensi yang dibutuhkan pustakawan generasi milenial dalam menghadapi perubahan paradigma layanan perpustakaan. Pembahasan mencakup soft skills, literasi digital, dan kemampuan adaptasi terhadap teknologi baru.',
    namaMedia: 'Khazanah Pustaka',
    jenisTerbitan: 'jurnal',
    volume: '8',
    nomor: '2',
    tanggalTerbit: '2024-07-30',
    tahunTerbit: 2024,
    halamanKolom: '89-102',
    kataKunci: ['pustakawan milenial', 'kompetensi', 'profesionalisme'],
    lokasiKoleksi: 'Rak Jurnal A-15',
    issn: '2355-9950',
  },
  {
    id: '7',
    judul: 'Ekonomi Kreatif dan Peran Perpustakaan sebagai Ruang Kolaborasi',
    pengarang: 'Hendra Wijaya',
    subjek: ['Ekonomi & Bisnis', 'Pustakawan & Perpustakaan'],
    abstrak: 'Perpustakaan modern tidak hanya tempat membaca, tetapi juga ruang kolaborasi bagi pelaku ekonomi kreatif. Artikel ini mengeksplorasi makerspace, co-working space, dan berbagai inovasi layanan perpustakaan untuk mendukung UMKM.',
    namaMedia: 'Intisari',
    jenisTerbitan: 'majalah',
    tanggalTerbit: '2024-05-01',
    tahunTerbit: 2024,
    halamanKolom: '34-40',
    kataKunci: ['ekonomi kreatif', 'makerspace', 'UMKM', 'kolaborasi'],
    lokasiKoleksi: 'Rak Majalah D-02',
  },
  {
    id: '8',
    judul: 'Pengembangan Koleksi Digital: Strategi Menghadapi Ledakan Informasi',
    pengarang: 'Dr. Agus Prasetyo',
    subjek: ['Literasi Digital', 'Pustakawan & Perpustakaan'],
    abstrak: 'Panduan praktis pengembangan koleksi digital yang efektif dan efisien. Pembahasan mencakup seleksi sumber digital, lisensi konten, preservasi jangka panjang, dan evaluasi penggunaan koleksi elektronik.',
    namaMedia: 'Buletin Perpusnas',
    jenisTerbitan: 'buletin',
    nomor: '45',
    tanggalTerbit: '2024-04-15',
    tahunTerbit: 2024,
    halamanKolom: '5-12',
    kataKunci: ['koleksi digital', 'pengembangan koleksi', 'e-resources'],
    lokasiKoleksi: 'Rak Buletin E-01',
  },
  {
    id: '9',
    judul: 'Bahasa Daerah di Ambang Kepunahan: Peran Perpustakaan dalam Dokumentasi',
    pengarang: 'Dr. Sri Wahyuni',
    subjek: ['Bahasa & Budaya'],
    abstrak: 'Indonesia memiliki lebih dari 700 bahasa daerah, namun banyak yang terancam punah. Artikel ini membahas peran perpustakaan dalam mendokumentasikan dan melestarikan bahasa daerah melalui koleksi khusus dan program komunitas.',
    namaMedia: 'Republika',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-02-21',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 15, Kol. 1-3',
    kataKunci: ['bahasa daerah', 'pelestarian', 'dokumentasi', 'warisan budaya'],
    lokasiKoleksi: 'Arsip Koran Feb 2024',
  },
  {
    id: '10',
    judul: 'Inovasi Layanan Referensi: Dari Meja Pustakawan ke Ruang Virtual',
    pengarang: 'Linda Kartika, M.Hum.',
    subjek: ['Pustakawan & Perpustakaan', 'Teknologi Informasi'],
    abstrak: 'Evolusi layanan referensi dari tradisional hingga virtual. Pembahasan mencakup implementasi chat reference, video consultation, dan penggunaan media sosial sebagai kanal layanan referensi modern.',
    namaMedia: 'Warta Pustakawan',
    jenisTerbitan: 'buletin',
    nomor: '32',
    tanggalTerbit: '2023-12-10',
    tahunTerbit: 2023,
    halamanKolom: '8-14',
    kataKunci: ['layanan referensi', 'virtual reference', 'inovasi layanan'],
    lokasiKoleksi: 'Rak Buletin E-02',
  },
  {
    id: '11',
    judul: 'Gerakan Indonesia Membaca: Evaluasi dan Proyeksi 2025',
    pengarang: 'Tim Redaksi Kompas',
    subjek: ['Literasi Anak', 'Pendidikan', 'Sosial Politik'],
    abstrak: 'Evaluasi komprehensif terhadap program Gerakan Indonesia Membaca yang telah berjalan selama lima tahun. Artikel menyoroti pencapaian, kendala, dan rekomendasi untuk meningkatkan indeks literasi nasional.',
    namaMedia: 'Kompas',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-01-02',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-6',
    kataKunci: ['literasi nasional', 'minat baca', 'kebijakan publik', 'evaluasi program'],
    lokasiKoleksi: 'Arsip Koran Jan 2024',
  },
  {
    id: '12',
    judul: 'Kesehatan Mental Pustakawan: Isu yang Terabaikan',
    pengarang: 'dr. Maya Sari, Sp.KJ',
    subjek: ['Kesehatan', 'Pustakawan & Perpustakaan'],
    abstrak: 'Studi tentang tingkat stres dan burnout di kalangan pustakawan Indonesia. Hasil survei menunjukkan perlunya program kesehatan mental dan keseimbangan kerja-kehidupan bagi profesi pustakawan.',
    namaMedia: 'Jurnal Perpustakaan',
    jenisTerbitan: 'jurnal',
    volume: '12',
    nomor: '3',
    tanggalTerbit: '2024-09-15',
    tahunTerbit: 2024,
    halamanKolom: '156-172',
    kataKunci: ['kesehatan mental', 'burnout', 'pustakawan', 'well-being'],
    lokasiKoleksi: 'Rak Jurnal B-05',
    issn: '2089-3612',
  },
  {
    id: '13',
    judul: 'Sastra Cyber: Fenomena Baru dalam Dunia Literasi',
    pengarang: 'Eka Putra Pratama',
    subjek: ['Seni & Sastra', 'Literasi Digital'],
    abstrak: 'Eksplorasi fenomena sastra cyber atau sastra digital yang berkembang di platform online. Pembahasan mencakup karakteristik, penerimaan pembaca, dan implikasinya terhadap pengembangan koleksi perpustakaan.',
    namaMedia: 'Tempo',
    jenisTerbitan: 'majalah',
    tanggalTerbit: '2024-10-28',
    tahunTerbit: 2024,
    halamanKolom: '54-58',
    kataKunci: ['sastra cyber', 'sastra digital', 'literasi', 'platform online'],
    lokasiKoleksi: 'Rak Majalah C-08',
  },
  {
    id: '14',
    judul: 'Perpustakaan dan Sustainable Development Goals (SDGs)',
    pengarang: 'Prof. Dr. Sulistyo Basuki',
    subjek: ['Pustakawan & Perpustakaan', 'Sosial Politik'],
    abstrak: 'Analisis kontribusi perpustakaan terhadap pencapaian Sustainable Development Goals (SDGs). Artikel mengidentifikasi peran strategis perpustakaan dalam mendukung 12 dari 17 tujuan SDGs.',
    namaMedia: 'Visi Pustaka',
    jenisTerbitan: 'jurnal',
    volume: '24',
    nomor: '3',
    tanggalTerbit: '2024-09-30',
    tahunTerbit: 2024,
    halamanKolom: '112-130',
    kataKunci: ['SDGs', 'pembangunan berkelanjutan', 'perpustakaan', 'kontribusi sosial'],
    lokasiKoleksi: 'Rak Jurnal A-12',
    issn: '1411-0199',
  },
  {
    id: '15',
    judul: 'Digitalisasi Arsip Kemerdekaan: Menyimpan Memori Bangsa',
    pengarang: 'Retno Wulandari',
    subjek: ['Bahasa & Budaya', 'Teknologi Informasi'],
    abstrak: 'Proyek digitalisasi arsip-arsip penting terkait kemerdekaan Indonesia yang tersimpan di berbagai perpustakaan dan arsip nasional. Upaya menjaga aksesibilitas dokumen sejarah untuk generasi mendatang.',
    namaMedia: 'Media Indonesia',
    jenisTerbitan: 'koran',
    tanggalTerbit: '2024-08-17',
    tahunTerbit: 2024,
    halamanKolom: 'Hal. 1, Kol. 1-4',
    kataKunci: ['digitalisasi', 'arsip', 'kemerdekaan', 'sejarah', 'preservasi'],
    lokasiKoleksi: 'Arsip Koran Ags 2024',
  },
];

export const statistics = {
  totalArticles: 2847,
  totalMedia: 45,
  yearRange: { start: 1985, end: 2024 },
  categories: {
    koran: 1245,
    jurnal: 856,
    majalah: 523,
    buletin: 223,
  },
};

export const getPublicationTypeLabel = (type: JenisTerbitan): string => {
  const labels: Record<JenisTerbitan, string> = {
    koran: 'Surat Kabar',
    jurnal: 'Jurnal Ilmiah',
    majalah: 'Majalah',
    buletin: 'Buletin',
  };
  return labels[type];
};

export const getPublicationTypeColor = (type: JenisTerbitan): string => {
  const colors: Record<JenisTerbitan, string> = {
    koran: 'bg-orange-500',
    jurnal: 'bg-blue-500',
    majalah: 'bg-purple-500',
    buletin: 'bg-emerald-500',
  };
  return colors[type];
};
